apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
    project: roboshop
    version: v1
    environmnet: dev
spec:
 containers:
 - name: frontend
   image: nginx
    