apiVersion: v1
kind: Pod
metadata: 
 name: env-demo
spec:
 containers:
 - name: nginx
   image: nginx
   env:
   - name: course
     value: k8
   - name: trainer
     value: shiva
   - name: joindevops
     value: online